/**
 * Iconoir 7.12.1 (MIT, iconoir.com): the Saddle family's icons.
 *
 * Generated by `npm run icons` (scripts/icons.mjs). Do not edit: change the
 * manifest in the script and run it again. Each file in assets/icons/ is
 * also the allowlist for a module descriptor’s `icon` and `tab_icons`.
 */
import { ReactComponent as Activity } from '../../../assets/icons/activity.svg';
import { ReactComponent as ArrowLeft } from '../../../assets/icons/arrow-left.svg';
import { ReactComponent as ArrowRight } from '../../../assets/icons/arrow-right.svg';
import { ReactComponent as ArrowSeparate } from '../../../assets/icons/arrow-separate.svg';
import { ReactComponent as ArrowUpRight } from '../../../assets/icons/arrow-up-right.svg';
import { ReactComponent as Bell } from '../../../assets/icons/bell.svg';
import { ReactComponent as Brain } from '../../../assets/icons/brain.svg';
import { ReactComponent as Check } from '../../../assets/icons/check.svg';
import { ReactComponent as CheckCircle } from '../../../assets/icons/check-circle.svg';
import { ReactComponent as Clock } from '../../../assets/icons/clock.svg';
import { ReactComponent as Copy } from '../../../assets/icons/copy.svg';
import { ReactComponent as DashboardDots } from '../../../assets/icons/dashboard-dots.svg';
import { ReactComponent as Download } from '../../../assets/icons/download.svg';
import { ReactComponent as Drag } from '../../../assets/icons/drag.svg';
import { ReactComponent as EditPencil } from '../../../assets/icons/edit-pencil.svg';
import { ReactComponent as Eye } from '../../../assets/icons/eye.svg';
import { ReactComponent as EyeClosed } from '../../../assets/icons/eye-closed.svg';
import { ReactComponent as Filter } from '../../../assets/icons/filter.svg';
import { ReactComponent as Flash } from '../../../assets/icons/flash.svg';
import { ReactComponent as Globe } from '../../../assets/icons/globe.svg';
import { ReactComponent as GraphUp } from '../../../assets/icons/graph-up.svg';
import { ReactComponent as Group } from '../../../assets/icons/group.svg';
import { ReactComponent as HelpCircle } from '../../../assets/icons/help-circle.svg';
import { ReactComponent as HomeSimpleDoor } from '../../../assets/icons/home-simple-door.svg';
import { ReactComponent as InfoCircle } from '../../../assets/icons/info-circle.svg';
import { ReactComponent as Key } from '../../../assets/icons/key.svg';
import { ReactComponent as Link } from '../../../assets/icons/link.svg';
import { ReactComponent as List } from '../../../assets/icons/list.svg';
import { ReactComponent as Lock } from '../../../assets/icons/lock.svg';
import { ReactComponent as MagicWand } from '../../../assets/icons/magic-wand.svg';
import { ReactComponent as Mail } from '../../../assets/icons/mail.svg';
import { ReactComponent as MailIn } from '../../../assets/icons/mail-in.svg';
import { ReactComponent as MailOut } from '../../../assets/icons/mail-out.svg';
import { ReactComponent as Minus } from '../../../assets/icons/minus.svg';
import { ReactComponent as MoreHoriz } from '../../../assets/icons/more-horiz.svg';
import { ReactComponent as MoreVert } from '../../../assets/icons/more-vert.svg';
import { ReactComponent as MultiplePages } from '../../../assets/icons/multiple-pages.svg';
import { ReactComponent as NavArrowDown } from '../../../assets/icons/nav-arrow-down.svg';
import { ReactComponent as NavArrowLeft } from '../../../assets/icons/nav-arrow-left.svg';
import { ReactComponent as NavArrowRight } from '../../../assets/icons/nav-arrow-right.svg';
import { ReactComponent as NavArrowUp } from '../../../assets/icons/nav-arrow-up.svg';
import { ReactComponent as OpenBook } from '../../../assets/icons/open-book.svg';
import { ReactComponent as OpenNewWindow } from '../../../assets/icons/open-new-window.svg';
import { ReactComponent as Page } from '../../../assets/icons/page.svg';
import { ReactComponent as PlugTypeA } from '../../../assets/icons/plug-type-a.svg';
import { ReactComponent as Plus } from '../../../assets/icons/plus.svg';
import { ReactComponent as Puzzle } from '../../../assets/icons/puzzle.svg';
import { ReactComponent as Refresh } from '../../../assets/icons/refresh.svg';
import { ReactComponent as RefreshDouble } from '../../../assets/icons/refresh-double.svg';
import { ReactComponent as Reports } from '../../../assets/icons/reports.svg';
import { ReactComponent as Search } from '../../../assets/icons/search.svg';
import { ReactComponent as SearchEngine } from '../../../assets/icons/search-engine.svg';
import { ReactComponent as SearchWindow } from '../../../assets/icons/search-window.svg';
import { ReactComponent as Send } from '../../../assets/icons/send.svg';
import { ReactComponent as SendMail } from '../../../assets/icons/send-mail.svg';
import { ReactComponent as Settings } from '../../../assets/icons/settings.svg';
import { ReactComponent as Shield } from '../../../assets/icons/shield.svg';
import { ReactComponent as ShieldCheck } from '../../../assets/icons/shield-check.svg';
import { ReactComponent as Sparks } from '../../../assets/icons/sparks.svg';
import { ReactComponent as Star } from '../../../assets/icons/star.svg';
import { ReactComponent as StatsReport } from '../../../assets/icons/stats-report.svg';
import { ReactComponent as Trash } from '../../../assets/icons/trash.svg';
import { ReactComponent as Upload } from '../../../assets/icons/upload.svg';
import { ReactComponent as User } from '../../../assets/icons/user.svg';
import { ReactComponent as ViewGrid } from '../../../assets/icons/view-grid.svg';
import { ReactComponent as WarningCircle } from '../../../assets/icons/warning-circle.svg';
import { ReactComponent as WarningTriangle } from '../../../assets/icons/warning-triangle.svg';
import { ReactComponent as Xmark } from '../../../assets/icons/xmark.svg';
import { ReactComponent as XmarkCircle } from '../../../assets/icons/xmark-circle.svg';

// Every icon, by its Iconoir name.
export const byName = {
	activity: Activity,
	'arrow-left': ArrowLeft,
	'arrow-right': ArrowRight,
	'arrow-separate': ArrowSeparate,
	'arrow-up-right': ArrowUpRight,
	bell: Bell,
	brain: Brain,
	check: Check,
	'check-circle': CheckCircle,
	clock: Clock,
	copy: Copy,
	'dashboard-dots': DashboardDots,
	download: Download,
	drag: Drag,
	'edit-pencil': EditPencil,
	eye: Eye,
	'eye-closed': EyeClosed,
	filter: Filter,
	flash: Flash,
	globe: Globe,
	'graph-up': GraphUp,
	group: Group,
	'help-circle': HelpCircle,
	'home-simple-door': HomeSimpleDoor,
	'info-circle': InfoCircle,
	key: Key,
	link: Link,
	list: List,
	lock: Lock,
	'magic-wand': MagicWand,
	mail: Mail,
	'mail-in': MailIn,
	'mail-out': MailOut,
	minus: Minus,
	'more-horiz': MoreHoriz,
	'more-vert': MoreVert,
	'multiple-pages': MultiplePages,
	'nav-arrow-down': NavArrowDown,
	'nav-arrow-left': NavArrowLeft,
	'nav-arrow-right': NavArrowRight,
	'nav-arrow-up': NavArrowUp,
	'open-book': OpenBook,
	'open-new-window': OpenNewWindow,
	page: Page,
	'plug-type-a': PlugTypeA,
	plus: Plus,
	puzzle: Puzzle,
	refresh: Refresh,
	'refresh-double': RefreshDouble,
	reports: Reports,
	search: Search,
	'search-engine': SearchEngine,
	'search-window': SearchWindow,
	send: Send,
	'send-mail': SendMail,
	settings: Settings,
	shield: Shield,
	'shield-check': ShieldCheck,
	sparks: Sparks,
	star: Star,
	'stats-report': StatsReport,
	trash: Trash,
	upload: Upload,
	user: User,
	'view-grid': ViewGrid,
	'warning-circle': WarningCircle,
	'warning-triangle': WarningTriangle,
	xmark: Xmark,
	'xmark-circle': XmarkCircle,
};

// `ui.icons`: each key and the Iconoir icon it is drawn with.
export const uiNames = {
	Activity: 'activity',
	AlertCircle: 'warning-circle',
	AlertTriangle: 'warning-triangle',
	ArrowLeft: 'arrow-left',
	ArrowLeftRight: 'arrow-separate',
	ArrowRight: 'arrow-right',
	ArrowUpRight: 'arrow-up-right',
	BarChart: 'stats-report',
	Bell: 'bell',
	BookOpen: 'open-book',
	Check: 'check',
	CheckCircle: 'check-circle',
	ChevronDown: 'nav-arrow-down',
	ChevronLeft: 'nav-arrow-left',
	ChevronRight: 'nav-arrow-right',
	ChevronUp: 'nav-arrow-up',
	Clock: 'clock',
	Copy: 'copy',
	Dashboard: 'dashboard-dots',
	Download: 'download',
	ExternalLink: 'open-new-window',
	Eye: 'eye',
	EyeOff: 'eye-closed',
	FileText: 'page',
	Filter: 'filter',
	Globe: 'globe',
	Grid: 'view-grid',
	Grip: 'drag',
	Help: 'help-circle',
	Home: 'home-simple-door',
	Inbox: 'mail-in',
	Info: 'info-circle',
	Key: 'key',
	Link: 'link',
	List: 'list',
	Loader: 'refresh-double',
	Lock: 'lock',
	Mail: 'mail',
	Minus: 'minus',
	MoreHorizontal: 'more-horiz',
	MoreVertical: 'more-vert',
	Pencil: 'edit-pencil',
	Plug: 'plug-type-a',
	Plus: 'plus',
	Refresh: 'refresh',
	Search: 'search',
	Send: 'send',
	Settings: 'settings',
	Shield: 'shield',
	ShieldCheck: 'shield-check',
	Sparkles: 'sparks',
	Star: 'star',
	Trash: 'trash',
	TrendingUp: 'graph-up',
	Upload: 'upload',
	User: 'user',
	Users: 'group',
	Wand: 'magic-wand',
	X: 'xmark',
	XCircle: 'xmark-circle',
	Zap: 'flash',
};

/**
 * An icon beside a label: the menu, a tab, the header. Decorative, so it is
 * hidden from assistive technology; the label beside it carries the name.
 *
 * @param {Object} props
 * @param {string} props.name Iconoir name.
 * @param {number} props.size Pixel size (16 in tabs, 20 in the header).
 * @return {?Element} The icon, or null for an unknown name.
 */
export function NavIcon( { name, size = 16 } ) {
	const Icon = Object.prototype.hasOwnProperty.call( byName, name )
		? byName[ name ]
		: null;
	if ( ! Icon ) {
		return null;
	}
	return (
		<Icon
			className="saddle-nav-icon"
			width={ size }
			height={ size }
			aria-hidden="true"
			focusable="false"
		/>
	);
}
